export const SET_USER_LOGINSTATE = 'SET_USER_LOGINSTATE';
export const GET_HEADER_NAV = 'GET_HEADER_NAV';
export const SET_PAGE_STATE = 'SET_PAGE_STATE';
export const ADMINLOGIN_FORM_STATE = 'ADMINLOGIN_FORM_STATE';
export const INDEX_CONTENT_LIST = 'INDEX_CONTENT_LIST';
export const CONTENT_DETAILS = 'CONTENT_DETAILS';
export const CONTENT_TAGS = 'CONTENT_TAGS';
export const CONTENT_HOTITEMS = 'CONTENT_HOTITEMS';
export const CONTENT_RECENTLYITEMS = 'CONTENT_RECENTLYITEMS';
export const CONTENT_INFOS = 'CONTENT_INFOS';
export const USER_MESSAGE_LIST = 'USER_MESSAGE_LIST';
export const USER_MESSAGE_FORM = 'USER_MESSAGE_FORM';
export const USER_LOGIN_FORM = 'USER_LOGIN_FORM';
export const SITEMAP_LIST = 'SITEMAP_LIST';
export const SYSTEMCONFIG_CONFIGLIST = 'SYSTEMCONFIG_CONFIGLIST';


