export const SET_HEADER_NAV = 'SET_HEADER_NAV';
export const GET_HEADER_NAV = 'GET_HEADER_NAV';
export const SET_HEADER_STATE = 'SET_HEADER_STATE';
export const ADMINLOGIN_FORM_STATE = 'ADMINLOGIN_FORM_STATE';
export const INDEX_CONTENT_LIST = 'INDEX_CONTENT_LIST';
export const CONTENT_DETAILS = 'CONTENT_DETAILS';


