export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADMINUSERFORMSTATE = 'ADMINUSERFORMSTATE';
export const ADMINUSERLIST = 'ADMINUSERLIST';
export const ADMINGROUP_FORMSTATE = 'ADMINGROUP_FORMSTATE';
export const ADMINGROUP_ROLEFORMSTATE = 'ADMINGROUP_ROLEFORMSTATE';
export const ADMINGROUP_LIST = 'ADMINGROUP_LIST';
export const ADMINRESOURCE_FORMSTATE = 'ADMINRESOURCE_FORMSTATE';
export const ADMINRESOURCE_LIST = 'ADMINRESOURCE_LIST';
export const CONTENTCATEGORYS_FORMSTATE = 'CONTENTCATEGORYS_FORMSTATE';
export const CONTENTCATEGORYS_LIST = 'CONTENTCATEGORYS_LIST';
export const CONTENT_FORMSTATE = 'CONTENT_FORMSTATE';
export const CONTENT_LIST = 'CONTENT_LIST';

