export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADMINUSERFORMSTATE = 'ADMINUSERFORMSTATE';
export const ADMINUSERLIST = 'ADMINUSERLIST';
export const ADMINGROUP_FORMSTATE = 'ADMINGROUP_FORMSTATE';
export const ADMINGROUP_ROLEFORMSTATE = 'ADMINGROUP_ROLEFORMSTATE';
export const ADMINGROUP_LIST = 'ADMINGROUP_LIST';

